In [1]:
import pandas as pd

c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
df = pd.read_csv("yelp_review.csv")

In [3]:
df

,review_id,user_id,business_id,stars,date,full_review_text,useful,funny,cool
0,vkVSCC7xljjrAI4UGfnKEQ,bv2nCi5Qv5vroFiqKGopiw,AEx2SYEUJmTxVVB18LlCwA,5,2016-05-28,Super simple place but amazing nonetheless. It...,0,0,0
1,n6QzIUObkYshz4dz2QRJTw,bv2nCi5Qv5vroFiqKGopiw,VR6GpWIda3SfvPC-lg9H3w,5,2016-05-28,Small unassuming place that changes their menu...,0,0,0
2,MV3CcKScW05u5LVfF6ok0g,bv2nCi5Qv5vroFiqKGopiw,CKC0-MOWMqoeWf6s-szl8g,5,2016-05-28,Lester's is located in a beautiful neighborhoo...,0,0,0
3,IXvOzsEMYtiJI0CARmj77Q,bv2nCi5Qv5vroFiqKGopiw,ACFtxLv8pGrrxMm6EgjreA,4,2016-05-28,Love coming here. Yes the place always needs t...,0,0,0
4,L_9BTb55X0GDtThi6GlZ6w,bv2nCi5Qv5vroFiqKGopiw,s2I_Ni76bjJNK9yG60iD-Q,4,2016-05-28,Had their chocolate almond croissant and it wa...,0,0,0
...,...,...,...,...,...,...,...,...,...
5261663,PoGSiNz1X5SUu0qEt-qM5w,mPjPyipaD0C_myqWqDipZg,Ngk84Ax1tXgpoJFEGxot3w,1,2011-11-21,"Bought groupon $39 for 4 months from groupon, ...",36,3,3
5261664,-CJNPrDWgIkorx4iEZJXIg,mPjPyipaD0C_myqWqDipZg,pOEL97ld-FJMKO8Ki8JmYg,3,2016-04-30,"Spring rolls was pretty good, cod was a bit ra...",0,0,0
5261665,W9eVvOcpBvG6lpJPoJOxuA,mPjPyipaD0C_myqWqDipZg,5ubokMNw8qfbX2WtxgJG1Q,4,2011-10-23,"Had a 8 dish set meal, was enough for 10 peopl...",3,0,1
5261666,hqQ1UTFKMN2P1ezUow48OQ,mPjPyipaD0C_myqWqDipZg,EO3i5kTUG7_S2OIQ23sdSA,3,2011-11-07,"A small, cozy family run Authentic korean rest...",2,0,0
5261667,ldsIs3sGXPJ7WM7VyAm4lQ,mPjPyipaD0C_myqWqDipZg,HloEEXm_QzEpycuwA_RtQA,3,2011-11-15,Really nice atmosphere and settings and very c...,0,1,1

In [77]:
def create_chunk(data,start_size,end_size):
    chunk = data.iloc[start_size:end_size]
    return chunk

In [94]:
data_chunks = []
smaller_chunks_count = 9
larger_chunks_count = 6
LARGER_CHUNK_SIZE = 1000000
SMALLER_CHUNK_SIZE = 625000
LAST_CHUNK_SIZE = 261668
start_slice = 0
chunk_slice = SMALLER_CHUNK_SIZE

for i in range(smaller_chunks_count):
    if i == smaller_chunks_count:
        chunk_slice = start_slice + LAST_CHUNK_SIZE
        data_chunks.append(create_chunk(df,start_slice,LAST_CHUNK_SIZE))
    else:
        data_chunks.append(create_chunk(df,start_slice,chunk_slice))
        start_slice += SMALLER_CHUNK_SIZE
        chunk_slice += SMALLER_CHUNK_SIZE

In [95]:
dataset_total = 0
for i in range(smaller_chunks_count):
    dataset_total += data_chunks[i].shape[0]
    print(data_chunks[i].shape)

print(dataset_total, dataset_total == df.shape[0])

(625000, 9)
(625000, 9)
(625000, 9)
(625000, 9)
(625000, 9)
(625000, 9)
(625000, 9)
(625000, 9)
(261668, 9)
5261668 True

In [96]:
filepath = 'smaller_chunks/chunk_'

In [97]:
for itr,chunk in enumerate(data_chunks):
    chunk.to_csv(filepath + str(itr + 1) + '.csv',index=False)